### ISSUE TITLE
Concerns about contribution to deployd

### ISSUE THREAD

**Issue by rgolea** [hoangtrongphuc/deployd-push-dashboard#1]
Hey there!

Nice work on this project. I'm really looking forward to use this in my projects. Here are some of my concerns about this:

1) The module might not be easy to search. If you look at [this link](https://github.com/deployd/deployd/blob/master/CONTRIBUTING.md) you can see that it's recommendable to use a `dpd` prefix. If you can change the name to `dpd-push-dashboard` or `dpd-push-notifications` it would be great.
2) It seems like this project depends on Firebase. I know Firebase is basically Google. But there is always a chance for it to drop since Parse was Facebook and it's not anymore. Can you do this project so it's not dependable on Firebase?

Thank you and keep up the good work!

**Comment by hoangtrongphuc** [comment]
1. Ok. Thanks for feedback and I will change to dpd-push-dashboard
2. Google will not support GCM in the future, and suggest upgrade to FCM
   FCM is upgrade version of GCM. If u like, u can make branch for other push method. It's simple and fast
