### ISSUE TITLE
error code E404

### ISSUE THREAD

**Issue by benslamajihed** [hoangtrongphuc/deployd-push-dashboard#2]
when  i  try  to  do  this  : npm install --save deployd-push-dashboard
Log : 
error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "deployd-push-dashboard" "--save"
33 error node v6.8.1
34 error npm  v3.10.8
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/deployd-push-dashboard
37 error 404
38 error 404 'deployd-push-dashboard' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

**Comment by hoangtrongphuc** [comment]
Please use npm i dpd-push-dashboard
