### ISSUE TITLE
Custom Notification

### ISSUE THREAD

**Issue by kkrishnan90** [hoangtrongphuc/deployd-push-dashboard#3]
Is there any way to send notification to particular device(device to device without the use of panel) ? If not, I would appreciate it if you take this as an enhancement.

**Comment by hoangtrongphuc** [comment]
What do u mean? If u want to send noti to particular device, simple you only copy regToken of this device to list users and send push.

**Comment by kkrishnan90** [comment]
I meant from one device to another .. rather than pushing the notif from backend or dashboard.. hope you got my point ?

**Comment by kkrishnan90** [comment]
I mean through client codes .. For example, if I might need to send a notification from my android device to my friends android device (like if I approve his friends request in my custom built app)..

**Comment by hoangtrongphuc** [comment]
No. You can't do that. We don't have control with client device and my project only support send push from server to client.
